site_name: carefree-learn
site_description: A minimal AutoML solution based on PyTorch.
site_author: carefree0910

repo_name: carefree0910/carefree-learn
repo_url: https://github.com/carefree0910/carefree-learn/
edit_uri: ""

copyright: 'Copyright &copy; 2019 - 2020 Yujian He'

theme:
    name: material

    highlightjs: true
    hljs_languages:
        - yaml
        - django

plugins:
    - search
    - minify:
        minify_html: true

extra:
  font:
    text: Roboto
    code: Roboto Mono
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/carefree0910

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - def_list
    - attr_list
    - footnotes
    - tables
    - abbr
    - pymdownx.mark
    - pymdownx.arithmatex
    - pymdownx.inlinehilite
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"

nav:
- Home: "index.md"
- Introduction: "introduction.md"
- User Guide:
    - Configurations: "user-guide/configurations.md"
- About:
    - Release Notes: "about/release-notes.md"
    - License: "about/license.md"
